### ISSUE TITLE
beaufortscale state class not supported

### ISSUE THREAD

**Issue by Anto79-ops** [bachya/ecowitt2mqtt#1016]
**Describe the bug**
Hello!

HA database/stats is telling me that the state class of the Beaufort sensor `The state class '' of this entity is not supported.` with the following message from the Statistics page:

```
Unsupported state class
The state class of this entity, is not supported.

Statistics cannot be generated until this entity has a supported state class.
If this state class was provided by an integration, this is a bug. Please report an issue.
If you have set this state class yourself, please correct it. [The different state classes and when to use which can be found in the developer documentation.](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
If the state class has permanently changed, you may want to delete the long term statistics of it from your database.
Do you want to permanently delete the long term statistics of sensor.beaufortscale from your database?

```

running 2024.6.1 on RPi thanks

**Comment by bachya** [comment]
The Beaufort Scale sensor actually wouldn't be a candidate for a state class. From their [docs](https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes) (specifically, [this section](https://developers.home-assistant.io/docs/core/entity/sensor#how-to-choose-state_class-and-last_reset)), we can deduce that state classes are intended to apply to numeric values (since they're used to generate statistics). This sensor outputs text values, which don't meet that criteria.

**Comment by Anto79-ops** [comment]
Good to know!
