### ISSUE TITLE
Battery reporting issues

### ISSUE THREAD

**Issue by w1ll1am23** [bachya/ecowitt2mqtt#113]
**ecowitt2mqtt version**
2022.01.0

**Describe the bug**
Using a gw1100 and have a WH32M connected to channel one. The battery is reported to home assistant but has a state of unknown. 

The value passed is on/off

Not sure if this is a HA issue or not. 

Another issue, again could be HA is my weather station (ws-5000) reports battery as a voltage but in HA it thinks 3.16v is low whej really thats 100%. This trips my low battery alerts. 

**To Reproduce**
Same as above 

**Expected behavior**
Issue with battery on channel 1 should be reporting on/off 

The other issue I'm not sure how it should be handled. 

![Screenshot_20220324-191411_Home_Assistant](https://user-images.githubusercontent.com/6432770/160025021-e3190bc8-9e01-4783-b416-621918e519d3.png)
![Screenshot_20220324-191420_Home_Assistant](https://user-images.githubusercontent.com/6432770/160025023-d6ba4f83-ec7e-49b6-a0b9-a3d1a8e92fb3.png)

**Additional context**

**Comment by bachya** [comment]
Had some life stuff come up, but haven't lost sight of this; will get to it as soon as I can!

**Comment by w1ll1am23** [comment]
Not a problem, totally understand!

**Comment by bachya** [comment]
@w1ll1am23 I'm back! Would love your help in diagnosing further.

Unfortunately, these devices are all over the place when it comes to representing battery values – as such, I have to have this (rather gross) helper to determine what I'm looking at:

https://github.com/bachya/ecowitt2mqtt/blob/155b11696effb81f7d15e2fe5f22f99d4ad1d665/ecowitt2mqtt/util/battery.py#L8-L21

Would you mind providing a HASS diagnostics dump of this device?

**Comment by w1ll1am23** [comment]
https://www.toptal.com/developers/hastebin/mivoguneca.json

**Comment by bachya** [comment]
Thanks! To confirm, we're investigating 2 issues:

1. `batt1` is showing an `unknown` state.
2. `wh80batt` is showing a `3.16` state and HASS is interpreting that as a low battery (when it shouldn't).

Is that correct?

**Comment by w1ll1am23** [comment]
That is correct.

**Comment by bachya** [comment]
### Issue 1: `batt1` showing an unknown state

This issue was fixed in #109, but I haven't cut a new release since 2022.01.0 (what you're using). You can use the `dev` docker image or install the `dev` branch directly, but if you'd prefer a pinned version, hang in there: I'll cut a new one soon.

(Background info, in case you're interested: https://github.com/home-assistant/core/issues/65640#issuecomment-1031302211)

### Issue 2: `wh80batt` showing a `3.16` state,, and HASS is interpreting that as a low battery (when it shouldn't)

Your diagnostics show your device is sending a value of 3.16, so that value (and unit) is correct. There's nothing in `ecowitt2mqtt` that tags that as a "low battery" – I wonder if that's something in your automation? Can you share that?

**Comment by w1ll1am23** [comment]
Nice, glad to hear the batt1 will start working. 

The other makes sense figured it was an issue with HA. 

I'm using this blue print. 

https://gist.github.com/sbyx/1f6f434f0903b872b84c4302637d0890

I think it probably needs to consider units and is assuming the 3.16 in my cases is a % not v

**Comment by bachya** [comment]
That looks right. 👍🏻 

Given that this issue is addressed, going to close. I will cut a new version today!
