### ISSUE TITLE
No longer getting lux value after upgrade

### ISSUE THREAD

**Issue by w1ll1am23** [bachya/ecowitt2mqtt#358]
**Describe the bug**
Upgraded last night and noticed this morning that my lux value is stuck at 0. Not seeing the value in the verbose logs.

I see solar radiation in W/m2 but no longer see a standalone lux sensor. 

Maybe this was intentional and I just need to do the conversion myself in HA?

**To Reproduce**
Running latest version with a weather station that outputs lux to a gw1100

**Diagnostics**
Output from using the `--diagnostics` flag.

**Additional context**

**Comment by bachya** [comment]
When I implemented customized units per entity category (https://github.com/bachya/ecowitt2mqtt/issues/308), I made lux a unit conversion of the existing `solarradiation` sensors (rather than its own sensor). From [the docs](https://github.com/bachya/ecowitt2mqtt#illuminance):

> #### Illuminance
> 
> Config Option: `--output-unit-illuminance`
> 
> * `fc`
> * `kfc`
> * `klx`
> * `lx`
> * `W/m²`

So, give `--output-unit-illuminance=lx` a try.

**Comment by w1ll1am23** [comment]
Ahh, thanks I should have dug around more assumed something like that was happening. Thanks.

**Comment by bachya** [comment]
No problem! Closing this issue as resolved, but if you run into any trouble, post back here.

**Comment by w1ll1am23** [comment]
This is working as expected using the above change. solar radiation is now reporting in lux. Thanks.
